version: "3.7"

services:
  # BSV DID Driver Service
  bsvdid-driver:
    platform: "linux/amd64"
    container_name: bsvdid-driver
    build:
      context: .
      dockerfile: docker/Dockerfile.jvm
    ports:
      - "9115:9115"  # Driver's exposed port
    environment:
      # Point to resolver in the same network
      BSV_RESOLVER_URL: "http://host.docker.internal:9111/"

      # Logging configuration
      QUARKUS_LOG_CONSOLE_JSON: "true"
      QUARKUS_LOG_LEVEL: "INFO"
      QUARKUS_LOG_CATEGORY__ORG_BSV__LEVEL: "DEBUG"
      QUARKUS_LOG_CONSOLE_JSON_ADDITIONAL_FIELD__origin__VALUE: "did-driver"
    networks:
      - did-network

networks:
  did-network:
    external: true